import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Brooke() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MR | Brooke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brooke's Page <a href="./">Home</a>
        </h1>



      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span class="mr-1 text-purple-600 text-xl font-semibold bg-clip-text hover:text-transparent hover:bg-gradient-to-br from-indigo-600 via-red-500 to-orange-400">
            MoveReady
          </span>
          <Image
            class=""
            src="/favicon-32x32.png"
            alt="MR Logo" 
            height={25}
            width={25}
          />
        </a>
      </footer>
    </div>
  )
}
