import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Brooke() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MR | Brooke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brooke's Page <a href="./">Home</a>
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
            Home
        </a>
      </footer>
    </div>
  )
}
