import Head from 'next/head'
import { Disclosure } from '@headlessui/react'

import styles from '../styles/Home.module.css'


function MyDisclosure() {
    return (
      <Disclosure>
        <Disclosure.Button className="py-2">
          Is team pricing available?
        </Disclosure.Button>
        <Disclosure.Panel className="text-yellow-500">
          Yes! You can purchase a license that you can share with your entire
          team.
        </Disclosure.Panel>
      </Disclosure>
    )
}

export default function Brooke() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MR | Brooke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brooke's Page <a href="./">Home</a>
        </h1>

        <MyDisclosure/>

      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
            Home
        </a>
      </footer>
    </div>
  )
}
