import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function User() {

    return (
        <div className={styles.container}>
            <Head>
                <title>MR</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
            
            </main>
        </div>
    )
}
